// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejfbwdsojuhvvooeztvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZmJ3ZHNvanVodnZvb2V6dHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Nzk2MjEsImV4cCI6MjA3NDE1NTYyMX0.ohZ7XPW8DEZG2xd2b8LE4xA-IhqWVI7wxDziG37j2-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  }
});